[tool.poetry]
name = "sjdata"
version = "0.1.0"
description = ""
authors = ["lcastrol <luis.a.castro.leiva@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
gobnb = "^0.0.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
